using PrinterMode.Core.Models;

namespace PrinterMode.Core.Interfaces;

public interface IWindowsPrinterService
{
    Task<bool> CreateTcpIpPortAsync(string portName, string ipAddress, int port, CancellationToken ct = default);
    Task<bool> CreateUsbPortAsync(string portName, CancellationToken ct = default);
    Task<bool> AddPrinterAsync(string printerName, string driverName, string portName, CancellationToken ct = default);
    Task<(bool ok, string? error)> TryAddPrinterWithReasonAsync(string printerName, string driverName, string portName, CancellationToken ct = default);
    Task<string?> TryRegisterPrintDriverFromInfAsync(string infPath, IReadOnlyList<string> candidateNames, CancellationToken ct = default);
    Task<(string? name, string? error)> TryRegisterPrintDriverFromInfWithReasonAsync(string infPath, IReadOnlyList<string> candidateNames, CancellationToken ct = default);
    Task<(bool ok, string? error)> TryRegisterUnsignedPrintDriverAsync(string driverName, string dataFilePath, IReadOnlyList<string> dependentFilePaths, CancellationToken ct = default);
    Task<bool> TryTrustCertificateAsync(string certPath, CancellationToken ct = default);
    Task<bool> PrinterExistsAsync(string printerName, CancellationToken ct = default);
    Task<string?> GetPrinterDriverAsync(string printerName, CancellationToken ct = default);
    Task<bool> UpdatePrinterPortAsync(string printerName, string newPortName, CancellationToken ct = default);
    Task<bool> AddSharedPrinterAsync(string connectionName, CancellationToken ct = default);
    Task<(bool ok, string error)> AddSharedPrinterInternalAsync(string connectionName, CancellationToken ct);
    Task<bool> SetPaperFormAsync(string printerName, PaperConfig paper, CancellationToken ct = default);
    Task<bool> SetDefaultPrinterAsync(string printerName, CancellationToken ct = default);
    Task<bool> DeletePrinterAsync(string printerName, CancellationToken ct = default);
    Task<bool> PrintTestPageAsync(string printerName, CancellationToken ct = default);
    Task<IReadOnlyList<string>> GetInstalledPrintersAsync(CancellationToken ct = default);
    Task<IReadOnlyList<string>> GetInstalledDriversAsync(CancellationToken ct = default);
    Task<IReadOnlyList<string>> GetAvailablePortsAsync(CancellationToken ct = default);
    Task<string?> FindBestUsbPortAsync(CancellationToken ct = default);
    Task<string?> FindBestUsbPortViaPowerShellAsync(CancellationToken ct = default);
    Task<string?> FindAnyUsbPrinterPortAsync(CancellationToken ct = default);
    Task<string?> FindNewPortSinceSnapshotAsync(IReadOnlyList<string> portsBefore, CancellationToken ct = default);
    Task<string?> FindUsbPortFromRegistryAsync(CancellationToken ct = default);
    Task<string?> FindDevicePortByVidPidAsync(string vid, string pid, CancellationToken ct = default);
    Task<string?> FindUsbPrintDeviceInterfacePathAsync(string vid, string pid, CancellationToken ct = default);
    Task<bool> EnsurePortRegisteredAsync(string portName, CancellationToken ct = default);
    Task<(bool ok, string? error)> TryRegisterPortWithReasonAsync(string portName, CancellationToken ct = default);
    Task<string> GetUsbDeviceDiagnosticsAsync(string vid, string pid, CancellationToken ct = default);
    Task<IReadOnlyList<string>> GetPrintMonitorsAsync(CancellationToken ct = default);
    Task<IReadOnlyList<string>> GetPortsForMonitorAsync(string monitorName, CancellationToken ct = default);
    Task<DetectedUsbDevice?> ResolvePrinterUsbDeviceAsync(IReadOnlyList<string> nameHints, string? catalogVid, string? catalogPid, CancellationToken ct = default);
    Task<string> ListConnectedUsbDevicesAsync(CancellationToken ct = default);
    Task TriggerPnpScanAsync(CancellationToken ct = default);
    Task ReEnumerateUsbPrinterDevicesAsync(CancellationToken ct = default);
    Task ReEnumerateDeviceByVidPidAsync(string vid, string pid, CancellationToken ct = default);
    Task<string?> ForceUsbPortFromUsbPrintAsync(string vid, string pid, CancellationToken ct = default);
    Task<IReadOnlyList<PortEntry>> GetSerialPortsWithNamesAsync(CancellationToken ct = default);
    Task<IReadOnlyList<PortEntry>> GetUsbPrinterPortsWithNamesAsync(CancellationToken ct = default);
    Task<string?> FindDriverNameFromAutoInstalledPrinterAsync(string manufacturerHint, string modelHint, CancellationToken ct = default);
    Task<(string? DriverName, string? PortName)> FindAutoInstalledPrinterInfoAsync(string manufacturerHint, string modelHint, CancellationToken ct = default);
    Task<string?> FindPortFromNewPrinterAsync(IReadOnlyList<string> printersBefore, CancellationToken ct = default);
    Task<(string? Name, string? DriverName, string? PortName)> FindNewlyCreatedPrinterAsync(IReadOnlyList<string> printersBefore, CancellationToken ct = default);
    Task<bool> EnsureGenericTextDriverAsync(CancellationToken ct = default);
    Task RestartSpoolerAsync(CancellationToken ct = default);
    Task<IReadOnlyList<string>> GetSharedPrintersAsync(string host, CancellationToken ct = default);
    Task<bool> CreateLprPortAsync(string portName, string host, string queueName, CancellationToken ct = default);
    Task EnableLpdServiceAsync(CancellationToken ct = default);
    Task<bool> TryEnableLpdRemotelyAsync(string host, CancellationToken ct = default);
    Task<bool> IsLpdAvailableAsync(string host, CancellationToken ct = default);
    Task<bool> SharePrinterAsync(string printerName, string shareName, CancellationToken ct = default);
    void StartDiscoveryListener();
    void StartLpdServer();
    Task<IReadOnlyList<string>> GetRemoteSharedPrintersAsync(string host, CancellationToken ct = default);
}
